export interface Order {
  id: string;
  invoice: string;
  userId: string | null;
  customerData: any;
  productId: string;
  productName: string;
  variantId: string;
  variantName: string;
  providerId: string;
  providerSkuId: string | null;
  providerSku: string | null;
  routingDecisionCode: string | null;
  quantity: number;
  price: number;
  adminFee: number;
  discount: number;
  loyaltyPointsUsed: number;
  loyaltyDiscountAmount: number;
  totalAmount: number;
  paymentStatus: string;
  transactionStatus: string;
  paymentGatewayCode: string | null;
  gatewayTransactionId: string | null;
  gatewayPaymentType: string | null;
  gatewayResponse: any | null;
  providerReferenceId: string | null;
  providerReference?: string | null;
  serialNumber: string | null;
  fulfillmentResponse: any | null;
  failureReason: string | null;
  idempotencyKey: string | null;
  paidAt: string | null;
  fulfilledAt: string | null;
  createdAt: string;
  updatedAt: string;
  promoId: string | null;
  promoSnapshot: any | null;
  flashSaleSnapshot: any | null;
  referralCode: string | null;
  snapToken: string | null;
  paymentUrl: string | null;
}
